name: "Safe Service Sync"
on:
  issues:
    types: [ opened ]
  issue_comment:
    types: [ created ]

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: "Safe Service Sync"
        uses: rmeissner/safe-service-monitor-gh-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          safe-address: '0xfF501B324DC6d78dC9F983f140B9211c3EdB4dc7'
          service-url: 'https://safe-transaction.mainnet.gnosis.io'