name: "Safe Tx Check"
on:
  issues:
    types: [ opened ]
  issue_comment:
    types: [ created ]

jobs:
  SafeTxCheck:
    runs-on: ubuntu-latest

    steps:
      - name: "Safe Tx Check"
        if: github.event.comment.body == 'recheck' || github.event_name == 'issues'
        # Beta Release
        uses: rmeissner/safe-tx-gh-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # the below token should have repo scope and must be manually added by you in the repository's secret
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          node-url: ${{ secrets.JSON_RPC_NODE }}
          safe-tx-hash: ${{ github.event.issue.body }}
          safe-address: '0x94D998c2Cb35bD4388D1D5Ed71992bF4a802d7a9'
          service-url: 'https://safe-transaction.rinkeby.gnosis.io'
          fail-on-unknown-delegatecall: 'false'
          # branch should not be protected
          branch: 'main'