name: "Safe Tx Check"
on:
  issues:
    types: [ opened ]
  issue_comment:
    types: [ created ]

jobs:
  CLAssistant:
    runs-on: ubuntu-latest

    steps:
      - name: "Safe Tx Check"
        if: github.event.comment.body == 'recheck' || github.event_name == 'issues'
        # Beta Release
        uses: rmeissner/safe-tx-gh-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # the below token should have repo scope and must be manually added by you in the repository's secret
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          safe-address: '0xA294e0Ccf64C9ef0BB3d43a736eCb932C0E47CFD'
          service-url: 'https://safe-transaction.rinkeby.gnosis.io/'
          # branch should not be protected
          branch: 'main'